config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/student_dashboard', as: :authenticated_student_dashboard
  get 'dashboards/staff_dashboard', as: :authenticated_staff_dashboard
  get 'dashboards/admin_dashboard', as: :authenticated_admin_dashboard

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :staffs, path: 'staffs', controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }
  devise_for :students, path: 'students', controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations',
    # confirmations: 'students/confirmations',
    # mailer: 'students/mailers',
    # passwords: 'students/passwords'
  }

  resources :students, only: [:index, :show]

  resources :admins do
    resources :departments
    resources :courses do
      resources :subjects
    end
  end

  resources :departments, only: [:index, :show]
  
  resources :courses, only: [:index, :show] do
    resources :subjects, only: [:index, :show] do
      resources :absents
      resources :presents
    end
  end

  root 'root#index'
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :department_staffs, dependent: :destroy
  has_many :departments, through: :department_staffs
  has_many :staff_courses, dependent: :destroy
  has_many :courses, through: :staff_courses
  has_many :subjects
  has_one_attached :image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/staffs/confirmations_controller.rb
class Staffs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staffs/omniauth_callbacks_controller.rb
class Staffs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staffs/passwords_controller.rb
class Staffs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staffs/registrations_controller.rb
class Staffs::RegistrationsController < Devise::RegistrationsController
  # include Accessible
  # skip_before_action :check_user, except: %i[new create]
  # skip_before_action :check_resource, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[attribute image name phone_number staff_registration_number national_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   root_path
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs/sessions_controller.rb
class Staffs::SessionsController < Devise::SessionsController
  # include Accessible
  # skip_before_action :check_user, only: :destroy
  # skip_before_action :check_resource, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/staffs/unlocks_controller.rb
class Staffs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[show edit update destroy]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show; end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit; end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to staff_url(@staff), notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to staff_url(@staff), notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_staff
    @staff = Staff.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def staff_params
    params.require(:staff).permit(:name, :national_id, :staff_registration_number, :phone_number, :image)
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :national_id, style: "display: block" %>
    <%= form.number_field :national_id %>
  </div>

  <div>
    <%= form.label :staff_registration_number, style: "display: block" %>
    <%= form.text_area :staff_registration_number %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.number_field :phone_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/_staff.html.erb
<div id="<%= dom_id staff %>">
  <p>
    <strong>Name:</strong>
    <%= staff.name %>
  </p>

  <p>
    <strong>National:</strong>
    <%= staff.national_id %>
  </p>

  <p>
    <strong>Staff registration number:</strong>
    <%= staff.staff_registration_number %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= staff.phone_number %>
  </p>

</div>

app/views/staffs/_staff_header.html.erb
<div id="<%= dom_id staff %>" class="header-layout">
  <%= image_tag staff.image, :style=>"height: 40px; width: 40px; border-radius: 50%" %>
  <p>
    <strong>Name:</strong>
    <%= staff.name %>
  </p>
  <p>
    <strong>National:</strong>
    <%= staff.national_id %>
  </p>
  <p>
    <strong>Staff registration number:</strong>
    <%= staff.staff_registration_number %>
  </p>
  <p>
    <strong>Phone number:</strong>
    <%= staff.phone_number %>
  </p>
</div>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Show this staff", @staff %> |
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Staffs</h1>

<div id="staffs">
  <% @staffs.each do |staff| %>
    <%= render staff %>
    <p>
      <%= link_to "Show this staff", staff %>
    </p>
  <% end %>
</div>

<%= link_to "New staff", new_staff_path %>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @staff %>

<div>
  <%= link_to "Edit this staff", edit_staff_path(@staff) %> |
  <%= link_to "Back to staffs", staffs_path %>

  <%= button_to "Destroy this staff", @staff, method: :delete %>
</div>