config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/student_dashboard', as: :authenticated_student_dashboard
  get 'dashboards/staff_dashboard', as: :authenticated_staff_dashboard
  get 'dashboards/admin_dashboard', as: :authenticated_admin_dashboard

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :staffs, path: 'staffs', controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }
  devise_for :students, path: 'students', controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations',
    # confirmations: 'students/confirmations',
    # mailer: 'students/mailers',
    # passwords: 'students/passwords'
  }

  resources :students, only: [:index, :show]

  resources :admins do
    resources :departments
    resources :courses do
      resources :subjects
    end
  end

  resources :departments, only: [:index, :show]
  
  resources :courses, only: [:index, :show] do
    resources :subjects, only: [:index, :show] do
      resources :absents
      resources :presents
    end
  end

  root 'root#index'
end

app/models/absent.rb
class Absent < ApplicationRecord
  has_and_belongs_to_many :students
  has_and_belongs_to_many :subjects
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :departments
  has_one_attached :image, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :staff_courses, dependent: :destroy
  has_many :staff, through: :staff_courses
  has_many :student_courses, dependent: :destroy
  has_many :students, through: :student_courses
  has_many :subjects
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :admin
  has_many :courses
  has_many :students
  has_many :department_staffs, dependent: :destroy
  has_many :staffs, through: :department_staffs
end

app/models/department_staff.rb
class DepartmentStaff < ApplicationRecord
  belongs_to :department
  belongs_to :staff
end

app/models/present.rb
class Present < ApplicationRecord
  has_and_belongs_to_many :students
  has_and_belongs_to_many :subjects
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :department_staffs, dependent: :destroy
  has_many :departments, through: :department_staffs
  has_many :staff_courses, dependent: :destroy
  has_many :courses, through: :staff_courses
  has_many :subjects
  has_one_attached :image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/staff_course.rb
class StaffCourse < ApplicationRecord
  belongs_to :staff
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :department
  has_many :student_courses, dependent: :destroy
  has_many :courses, through: :student_courses
  has_and_belongs_to_many :subjects
  has_and_belongs_to_many :presents
  has_and_belongs_to_many :absents
  has_one_attached :image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def self.search(search)
    if search
      student = Student.find_by(name: search)
      if student
        self.where(student_id: student)
      else
        Student.all
      end
    else
      Student.all
    end
  end
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :course
  has_and_belongs_to_many :staff
  has_and_belongs_to_many :students
  has_and_belongs_to_many :presents
  has_and_belongs_to_many :absents
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  before_action :set_present, only: %i[show edit update destroy]

  # GET /presents or /presents.json
  def index
    @presents = Present.all
  end

  # GET /presents/1 or /presents/1.json
  def show; end

  # GET /presents/new
  def new
    @present = Present.new
  end

  # GET /presents/1/edit
  def edit; end

  # POST /presents or /presents.json
  def create
    @present = Present.new(present_params)

    respond_to do |format|
      if @present.save
        format.html { redirect_to present_url(@present), notice: 'Present was successfully created.' }
        format.json { render :show, status: :created, location: @present }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presents/1 or /presents/1.json
  def update
    respond_to do |format|
      if @present.update(present_params)
        format.html { redirect_to present_url(@present), notice: 'Present was successfully updated.' }
        format.json { render :show, status: :ok, location: @present }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presents/1 or /presents/1.json
  def destroy
    @present.destroy

    respond_to do |format|
      format.html { redirect_to presents_url, notice: 'Present was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_present
    @present = Present.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def present_params
    params.require(:present).permit(:student_id, :subject_id, :subject_date)
  end
end

app/helpers/absents_helper.rb
module AbsentsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/presents/_form.html.erb
<%= form_with(model: present) do |form| %>
  <% if present.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(present.errors.count, "error") %> prohibited this present from being saved:</h2>

      <ul>
        <% present.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :subject_id, style: "display: block" %>
    <%= form.text_field :subject_id %>
  </div>

  <div>
    <%= form.label :subject_date, style: "display: block" %>
    <%= form.date_field :subject_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/presents/_present.html.erb
<div id="<%= dom_id present %>">
  <p>
    <strong>Student:</strong>
    <%= present.student_id %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= present.subject_id %>
  </p>

  <p>
    <strong>Subject date:</strong>
    <%= present.subject_date %>
  </p>

</div>

app/views/presents/edit.html.erb
<h1>Editing present</h1>

<%= render "form", present: @present %>

<br>

<div>
  <%= link_to "Show this present", @present %> |
  <%= link_to "Back to presents", presents_path %>
</div>

app/views/presents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Presents</h1>

<div id="presents">
  <% @presents.each do |present| %>
    <%= render present %>
    <p>
      <%= link_to "Show this present", present %>
    </p>
  <% end %>
</div>

<%= link_to "New present", new_present_path %>

app/views/presents/new.html.erb
<h1>New present</h1>

<%= render "form", present: @present %>

<br>

<div>
  <%= link_to "Back to presents", presents_path %>
</div>

app/views/presents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @present %>

<div>
  <%= link_to "Edit this present", edit_present_path(@present) %> |
  <%= link_to "Back to presents", presents_path %>

  <%= button_to "Destroy this present", @present, method: :delete %>
</div>