config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/student_dashboard', as: :authenticated_student_dashboard
  get 'dashboards/staff_dashboard', as: :authenticated_staff_dashboard
  get 'dashboards/admin_dashboard', as: :authenticated_admin_dashboard

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  
  devise_for :staffs, path: 'staffs', controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }
  devise_for :students, path: 'students', controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations',
    # confirmations: 'students/confirmations',
    # mailer: 'students/mailers',
    # passwords: 'students/passwords'
  }

  resources :students, only: [:index, :show]

  resources :admins do
    resources :departments
    resources :courses do
      resources :subjects
    end
  end

  resources :departments, only: [:index, :show]
  
  resources :courses, only: [:index, :show] do
    resources :subjects, only: [:index, :show] do
      resources :absents
      resources :presents
    end
  end

  root 'root#index'
end

app/models/absent.rb
class Absent < ApplicationRecord
  has_and_belongs_to_many :students
  has_and_belongs_to_many :subjects
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :departments
  has_one_attached :image, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :staff_courses, dependent: :destroy
  has_many :staff, through: :staff_courses
  has_many :student_courses, dependent: :destroy
  has_many :students, through: :student_courses
  has_many :subjects
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :admin
  has_many :courses
  has_many :students
  has_many :department_staffs, dependent: :destroy
  has_many :staffs, through: :department_staffs
end

app/models/department_staff.rb
class DepartmentStaff < ApplicationRecord
  belongs_to :department
  belongs_to :staff
end

app/models/present.rb
class Present < ApplicationRecord
  has_and_belongs_to_many :students
  has_and_belongs_to_many :subjects
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :department_staffs, dependent: :destroy
  has_many :departments, through: :department_staffs
  has_many :staff_courses, dependent: :destroy
  has_many :courses, through: :staff_courses
  has_many :subjects
  has_one_attached :image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/staff_course.rb
class StaffCourse < ApplicationRecord
  belongs_to :staff
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :department
  has_many :student_courses, dependent: :destroy
  has_many :courses, through: :student_courses
  has_and_belongs_to_many :subjects
  has_and_belongs_to_many :presents
  has_and_belongs_to_many :absents
  has_one_attached :image, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def self.search(search)
    if search
      student = Student.find_by(name: search)
      if student
        self.where(student_id: student)
      else
        Student.all
      end
    else
      Student.all
    end
  end
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :course
  has_and_belongs_to_many :staff
  has_and_belongs_to_many :students
  has_and_belongs_to_many :presents
  has_and_belongs_to_many :absents
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # include Accessible
  # before_action :check_user
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show; end

  # GET /courses/new
  def new
    # @departments = Department.all
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:name, :code, :duration)
  end
end

app/helpers/absents_helper.rb
module AbsentsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= course.code %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= course.duration %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_area :code %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

    <div>
    <%= form.label :department, style: "display: block" %>
    <%# collection_select(:department, :department_id, current_admin.departments, :id, :name, {}, { multiple: :true}) %>
    <%= form.select :department_id, current_admin.departments.collect { |d| [d.name, d.id] }, include_blank: 'Select Department'%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>
<%= render "form", course: @course %>
<br>
<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<% if current_student || current_staff || current_admin %>
  <p style="color: green"><%= notice %></p>
  <h1>Courses</h1>
  <div id="courses">
    <% @courses.each do |course| %>
      <%= render course %>
      <p>
        <%= link_to "Show this course", course %>
      </p>
    <% end %>
  </div>
  <%= link_to "New course", new_admin_course_path(current_admin) %>
<% else %>
  <p>You need to login to see this</p>
<% end %>

app/views/courses/new.html.erb
<% if current_admin %>
  <h1>New course</h1>
  <%= render "form", course: @course %>
  <br>
  <div>
    <%= link_to "Back to courses", courses_path %>
  </div>
<% else %>
  <p>Only admins can add courses</p>
<% end %>

app/views/courses/show.html.erb
<% if current_student || current_staff || current_admin %>
  <p style="color: green"><%= notice %></p>
  <%= render @course %>
  <div>
    <% if current_admin %>
      <%= link_to "Edit this course", edit_course_path(@course) %> |
      <%= button_to "Destroy this course", @course, method: :delete %>
    <% end %>
    <%= link_to "Back to courses", courses_path %>
  </div>
<% else %>
  <p>Sign in to view more details</p>
<% end %>